- repo: https://gitlab.com/daverona-env/pre-commit-cpp
  rev: 0.6.0          # use the most recent version
  hooks:
  - id: cpplint       # linter (or style-error checker) for Google C++ Style Guide
    exclude: CMakeFiles

