sudo: false

language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install libopencv-dev
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install libeigen3-dev
  - sudo apt-get install libboost-all-dev

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

before_script:
  - mkdir build
  - cd build
  - cmake -D TESTS=ON ..

script:
  - make
  - ./tests

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7

    packages:
      - gcc-5
      - g++-5
      - clang-3.7